---
- name: Install influxgraph from pip
  become: yes
  become_user: "{{ graphite_api_system_user }}"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    virtualenv: "{{ graphite_api_venv_path }}"
  with_items:
    - { name: influxgraph, version: "{{ graphite_api_influxgraph_version }}" }
    - { name: influxdb, version: "{{ graphite_api_infludb_python_version }}" }
    - { name: tox, version: "{{ graphite_api_tox_version }}"}
  notify:
    - "restart {{ graphite_api_service_name }}"