---
- block:
  - name: Add graphite-api system user
    user:
      name: "{{ graphite_api_system_user }}"
      shell: /bin/bash
      group: "{{ graphite_api_system_group }}"
      append: yes
      createhome: yes
      home: "{{ graphite_api_home }}"

  - name: Delete virtualenv dir
    file:
      path: "{{ graphite_api_venv_path }}"
      state: absent
    when: graphite_api_force_recreate_venv

  - name: Install apt prerequisites
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python-pip
      - python-virtualenv

  - name: Install virtualenv from pip
    pip:
      name: "virtualenv"
      version: "{{ graphite_api_virtualenv_version }}"
  
  - import_tasks: graphite-api.yml
    tags:
      - graphite-api

  - import_tasks: influxgraph.yml
    tags:
      - influxgraph
  when: graphite_api_install_api

- import_tasks: influxdb.yml
  tags:
    - influxdb
