---
- name: Copy the SystemD unit file for graphite-api
  template:
    src: "etc/systemd/system/graphite_api_service_name.service.j2"
    dest: "/etc/systemd/system/{{ graphite_api_service_name }}.service"
  notify:
    - "restart {{ graphite_api_service_name }}"

- name: Enable the SystemD services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
  with_items:
    - "{{ graphite_api_service_name }}"
    - memcached