---
- name: restart {{ graphite_api_service_name }}
  systemd:
    name: "{{ graphite_api_service_name }}"
    state: restarted

- name: restart memcached
  systemd:
    name: memcached
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted